project 'ZJBL-GL.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZJBL-GL' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZJBL-GL

#    pod 'AFNetworking', '3.1.0'
#    pod 'SDWebImage', '3.8.1'
#    pod 'MJExtension','3.0.13'
#    pod 'MJRefresh','3.1.12'
   pod 'MBProgressHUD', '~> 1.0.0'
   pod 'Masonry','1.0.2'

  #target 'ZJBL-GLTests' do
   # inherit! :search_paths
    # Pods for testing
  #end

  #target 'ZJBL-GLUITests' do
   # inherit! :search_paths
    # Pods for testing
  #end

end
